### ISSUE TITLE
Fix installation and travis

### ISSUE THREAD

**Issue by stefanbschneider** [RealVNF/coord-env-interface#17]
Installation needs to work without `pip install git...` inside the setup.py.

This breaks the local installation where I have the simulator installed already.

Why do we need this now but not before?

Anything travis specific can still be installed in the Travis file.

Fix https://github.com/RealVNF/coord-env-interface/pull/16

**Comment by adnan904** [comment]
That was because of Travis giving me a headache yesterday. It requires the siminterface for the simulator while testing the Random Schedule Algo (Earlier was testing against the Dummy Environment). I will try to Install the coord-env-interface within travis and not in the setup.py file
